### ISSUE TITLE
HeliusAPI missing

### ISSUE THREAD

**Issue by Lmmb74** [AlphaHelixDev/AlphaLibary#2]
Hello. I was trying to compile the latest version of AlphaLibrary but I am unable to find where the HeliusAPI dependency could be downloaded. Thanks in advance for your help.

**Comment by HelixOW** [comment]
The current state of the AlphaLibary is a deeply developmental state, the Helius API will soon be available on github. It doesn't have is own download yet.

**Comment by Lmmb74** [comment]
Ok. Thanks. Truth is, I wanted to update UHC-Spigot to the latest version of Spigot and AlphaLibrary myself, but since I could not find HeliusAPI, I asked you to update it. Once HeliusAPI is uploaded, I would gladly update UHC-Spigot. Thanks for such a fast response :D

**Comment by HelixOW** [comment]
https://github.com/WhoIsAlphaHelix/HeliusAPI/releases
